apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-followers
  labels:
    app: hermes-followers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hermes-followers
  template:
    metadata:
      labels:
        app: hermes-followers
    spec:
      containers:
        - name: mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "1000m"
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: example
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://root:example@mongo:27017/
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "1000m"
        - name: hermes
          image: lptonussi/hermes
          imagePullPolicy: Always
          args: [
            "-j", "hermes-leader:9000"
          ]
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROTOCOL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PROTOCOL_PORT
              value: "10000"
          ports:
            - name: server
              containerPort: 8000
            - name: join
              containerPort: 9000
            - name: protocol
              containerPort: 10000
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      nodeSelector:
        role: server
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "hermes-leader", "hermes-follower" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
