apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes-leader
  labels:
    app: hermes-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hermes-leader
  template:
    metadata:
      labels:
        app: hermes-leader
    spec:
      containers:
        - name: mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongodb
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongodb
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "1000m"
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: mongodb
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: mongodb
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://mongodb:mongodb@mongo:27017/
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "1000m"
        - name: hermes
          image: lptonussi/hermes
          imagePullPolicy: Always
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PROTOCOL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PROTOCOL_PORT
              value: "10000"
          ports:
            - name: server
              containerPort: 8000
            - name: join
              containerPort: 9000
            - name: protocol
              containerPort: 10000
          resources:
            requests:
              memory: "300Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      nodeSelector:
        role: server
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: name
                    operator: In
                    values: [ "hermes-leader", "hermes-follower" ]
              topologyKey: failure-domain.beta.kubernetes.io/zone
---
apiVersion: v1
kind: Service
metadata:
  name: hermes-leader
spec:
  selector:
    app: hermes-leader
  type: NodePort
  ports:
    - name: server
      port: 8000
      targetPort: 8000
    - name: join
      port: 9000
      targetPort: 9000
